openapi: 3.0.3

info:
  title: Car Service API
  description: |-
    OpenAPI specification example based on Car model
  version: 0.0.2
  # API-first design

servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: car
  - name: comment

paths:
  "/comments":
    get:
      security:
        - BearerAuth: []
      tags:
        - comment
      summary: "Get all comments"
      description: "Fetch all existing car comments"
      operationId: getComments
      responses:
        '200':
          $ref: "#/components/responses/CommentList"
        '400':
          description: Invalid request
  "/cars":
    get:
      security:
        - BearerAuth: []
      tags:
        - car
      summary: "Get all cars"
      description: "Fetch all existing cars"
      operationId: getCars
      parameters:
        - in: query
          name: minEnginePower
          schema:
            type: integer
            format: int32
        - in: query
          name: maxEnginePower
          schema:
            type: integer
            format: int32
      responses:
        '200':
          $ref: "#/components/responses/CarList"
        '400':
          description: Invalid request
    post:
      security:
        - BearerAuth: []
      tags:
        - car
      summary: "Create car"
      operationId: createCar
      requestBody:
        $ref: "#/components/requestBodies/Car"
      responses:
        '201':
          $ref: "#/components/responses/Car"
        '400':
          description: Invalid request
        '422':
          description: Validation exception
  "/cars/{id}":
    get:
      security:
        - BearerAuth: []
      tags:
        - car
      summary: "Get specific car"
      description: "Get car by id"
      operationId: getCar
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: "Car ID"
      responses:
        '200':
          $ref: "#/components/responses/Car"
        '400':
          description: Invalid request
    put:
      security:
        - BearerAuth: []
      tags:
        - car
      summary: "Modify specific car"
      description: "Update only car properties included in the body"
      operationId: modifyCar
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: "Car ID"
      requestBody:
        $ref: "#/components/requestBodies/Car"
      responses:
        '201':
          $ref: "#/components/responses/Car"
        '400':
          description: Invalid request
        '422':
          description: Validation exception

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CarProduct:
      type: object
      properties:
        name:
          type: string
          example: "Миючий засіб 3000"
          minLength: 3
          maxLength: 64
        price:
          type: number
          format: double
          example: 63999.99
    Car:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          example: 10
        model:
          type: string
          example: "Car Model 1"
          minLength: 3
          maxLength: 64
        enginePower:
          type: integer
          format: int32
          example: 137
        torque:
          type: integer
          format: int32
          example: 220
        fuelType:
          type: string
        owner:
          type: string
        lastMaintenanceTimestamp:
          type: string
          format: date
          readOnly: true
        availableProducts:
          type: array
          items:
            $ref: "#/components/schemas/CarProduct"
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          example: 10
        author:
          type: string
          example: "Ruben Hauck"
          minLength: 3
          maxLength: 64
        text:
          type: string
          example: "Lorem ipsum"
  responses:
    Car:
      description: Car
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Car'
    CarList:
      description: Car list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Car'
    CommentList:
      description: Car list
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Comment'
  requestBodies:
    Car:
      description: Car to be created
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Car'